### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by IRONB0SS** [encoderpie/gamepad-api-test#8]
Hey Sir, first of all thank you for this tool, very useful

Could you Add detail to buttons and analogs when they pressed?
![image](https://github.com/encoderpie/gamepad-api-test/assets/97769328/39348e19-2331-4c95-a2e0-501d6d44d24e)

I use this [html5 gamepad tester](https://hardwaretester.com/gamepad) it shows details but no vibration test so it would be awesome have details too

**Comment by encoderpie** [comment]
Thank you for your feedback, I will add more details soon. If you have any other suggestions please let me know.

**Comment by IRONB0SS** [comment]
Hey again bro

It would be awesome to let us change vibration settings permanently
![Screenshot 2024-01-17 131313](https://github.com/encoderpie/gamepad-api-test/assets/97769328/2ca1c0ef-c820-4051-af7c-1bdeda39f197)
**Note : Save changes is hidden and it appears whenever you change vibration section settings**
 

Also add a line/dot in the middle of bar, this can help us to find out where is dead zone is
![Screenshot 2024-01-17 131514](https://github.com/encoderpie/gamepad-api-test/assets/97769328/629dc15d-54e7-4e4d-af34-9dfb4caf1b31)


and the last one, is it possible to have this too? [[Gamepad website](https://hardwaretester.com/gamepad)]
![image](https://github.com/encoderpie/gamepad-api-test/assets/97769328/bc3d9b3d-b126-48fd-8dd6-9eb389ed02f0)

Thanks in advance and best regards 🙌

**Comment by encoderpie** [comment]
Im taking note of them all, thank you for your contribution.

**Comment by IRONB0SS** [comment]
No problem bro 🙌

**Comment by encoderpie** [comment]
OLD:
![Ekran Görüntüsü - 2024-01-31 00-43-43](https://github.com/encoderpie/gamepad-api-test/assets/84232289/8e7609ea-834c-426f-b301-f41e9bedb966)

NEW:
![image](https://github.com/encoderpie/gamepad-api-test/assets/84232289/46bd445c-6fc4-4a94-b415-76802d48f2a0)

**Comment by IRONB0SS** [comment]
Hey bro, you just killing it, AMAZING WORK 🔥
really cannot wait to test new one, seems so professional

Also I have another question: Is it possible to test PS4/PS5 touch pad?

Edit : Okay I tested gamepad tester v2, I'm really enjoying using it and I'm grateful that you put your time on this 🙌

and here some bugs I found

• **sometimes Timestamp numbers are out of the box** :
![image](https://github.com/encoderpie/gamepad-api-test/assets/97769328/405f666f-1239-4046-b2ca-fcbd296c4aa8)

• **also this section doesn't hide after recognizing the controller**
![image](https://github.com/encoderpie/gamepad-api-test/assets/97769328/0b2a46d0-1fe9-445a-9a2c-ddf1981a5403)


**Feedback** :
it would be awesome If you put some info here with numbers when we changing parameters as a small popup
![image](https://github.com/encoderpie/gamepad-api-test/assets/97769328/54303cfe-cc1f-46b5-899c-f7179bc73239)

like this :
![Cursor](https://github.com/encoderpie/gamepad-api-test/assets/97769328/2f73a555-b1d6-4a5c-bb92-c5d8d3514ec8)


Thanks in advance 🙌❤️

**Comment by encoderpie** [comment]
@IRONB0SS I enjoy working on projects involving controllers of this style and make the most of my free time by engaging in them. Thank you for your interest ❤️ Additionally, reading touchpad data is currently impossible.

**Comment by encoderpie** [comment]
![image](https://github.com/encoderpie/gamepad-api-test/assets/84232289/6f170013-ee54-48d5-8f79-59f94f2a8bd8)

**Comment by IRONB0SS** [comment]
Thanks a lot, It's has been fixed now

One last request: I couldn't run this tool fully offline, I moved files to my main PC which is in my repair room with no internet connection (because it's underground there is no signal too) so I'm wondering if you can do something about it

**Comment by encoderpie** [comment]
You can run it offline when you download the project files and run the "index.html" file

**Comment by IRONB0SS** [comment]
Okay I found the solution, it requires the internet at the start-up only for one time

![gamepad-ezgif com-video-to-gif-converter](https://github.com/encoderpie/gamepad-api-test/assets/97769328/08dc1808-dcfd-46df-bbde-18a760b41cb6)

it would be nice if you could make a fully offline version, if not, there is no problem at all

I'm going to close this issue and again THANK YOU for your hard work and putting your time on this project

Good luck Arkadaşım ❤🙌

**Comment by IRONB0SS** [comment]
Hey again bro, We need some help here
Whenever chrome delete it's own cache, the tool needed online connection to load everything

Please do something about this at your free time, cheers

**Comment by IRONB0SS** [comment]
Hey again bro, We need some help here
Whenever chrome delete it's own cache, the tool needed online connection to load everything

Please do something about this at your free time, cheers
